version: '3.8'

services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    command: node main.js
    ports:
      - "3000-3003:3000-3003" # see the view from the camera mounted on your bot head: http://localhost:3000/

  viaproxy: #use this service to connect to an unsupported minecraft server versions. more info: ./services/viaproxy/README.md
    image: ghcr.io/viaversion/viaproxy:latest
    volumes:
      - ./services/viaproxy:/app/run
    ports:
      - "25568:25568"
    profiles:
      - viaproxy
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./services/mc:/data
    profiles:
      - mc

