const STOPPED = 0
const ACTIVE = 1
const PAUSED = 2
export class SelfPrompter {
    constructor(agent) {
        this.agent = agent;
        this.state = STOPPED;
        this.loop_active = false;
        this.interrupt = false;
        this.prompt = '';
        this.idle_time = 0;
        this.cooldown = 2000;
    }

    start(prompt) {
        console.log('Self-prompting started.');
        if (!prompt) {
            if (!this.prompt)
                return 'No prompt specified. Ignoring request.';
            prompt = this.prompt;
        }
        this.state = ACTIVE;
        this.prompt = prompt;
        this.startLoop();
    }

    isActive() {
        return this.state === ACTIVE;
    }

    isStopped() {
        return this.state === STOPPED;
    }

    isPaused() {
        return this.state === PAUSED;
    }

    async handleLoad(prompt, state) {
        if (state == undefined)
            state = STOPPED;
        this.state = state;
        this.prompt = prompt;
        if (state !== STOPPED && !prompt)
            throw new Error('No prompt loaded when self-prompting is active');
        if (state === ACTIVE) {
            await this.start(prompt);
        }
    }

    setPromptPaused(prompt) {
        this.prompt = prompt;
        this.state = PAUSED;
    }

    async startLoop() {
        if (this.loop_active) {
            console.warn('Self-prompt loop is already active. Ignoring request.');
            return;
        }
        console.log('[Self-Prompter] Starting self-prompt loop');
        this.loop_active = true;

        // --- RESILIENT RETRY LOGIC ---
        // Track consecutive failures (no command generated by the AI).
        // Original behavior: stop after 3 failures, never recover.
        // New behavior: after 3 failures, pause for 30 seconds and try again.
        // Only fully give up after 10 consecutive failures (across retries).
        // This prevents the bot from going permanently idle due to a temporary
        // API hiccup or a single bad prompt response.
        let no_command_count = 0;
        const MAX_NO_COMMAND_BEFORE_PAUSE = 3;  // pause and retry after this many
        const MAX_TOTAL_FAILURES = 10;           // fully stop after this many total

        while (!this.interrupt) {
            const msg = `You are self-prompting with the goal: '${this.prompt}'. Your next response MUST contain a command with this syntax: !commandName. Respond:`;

            let used_command = await this.agent.handleMessage('system', msg, -1);

            if (!used_command) {
                no_command_count++;
                console.warn(`[Self-Prompter] No command generated (${no_command_count}/${MAX_TOTAL_FAILURES} total failures)`);

                if (no_command_count >= MAX_TOTAL_FAILURES) {
                    // --- HARD STOP ---
                    // Too many consecutive failures. Something is fundamentally wrong
                    // (API down, model refusing, etc.). Stop to avoid burning tokens.
                    let out = `Agent failed to generate commands ${MAX_TOTAL_FAILURES} times in a row. Stopping self-prompting.`;
                    this.agent.openChat(out);
                    console.error('[Self-Prompter]', out);
                    this.state = STOPPED;
                    break;
                }

                if (no_command_count % MAX_NO_COMMAND_BEFORE_PAUSE === 0) {
                    // --- SOFT PAUSE ---
                    // After every 3 failures, wait 30 seconds before retrying.
                    // This gives the API time to recover from rate limits or outages,
                    // and prevents us from burning through tokens on empty responses.
                    console.log(`[Self-Prompter] Pausing for 30s after ${no_command_count} failures, then retrying...`);
                    await new Promise(r => setTimeout(r, 30000));
                }
            }
            else {
                // --- SUCCESS ---
                // Reset the failure counter on any successful command.
                // A single success means the system is working again.
                no_command_count = 0;
                await new Promise(r => setTimeout(r, this.cooldown));
            }
        }
        console.log('[Self-Prompter] Loop stopped');
        this.loop_active = false;
        this.interrupt = false;
    }

    update(delta) {
        // automatically restarts loop
        if (this.state === ACTIVE && !this.loop_active && !this.interrupt) {
            if (this.agent.isIdle())
                this.idle_time += delta;
            else
                this.idle_time = 0;

            if (this.idle_time >= this.cooldown) {
                console.log('Restarting self-prompting...');
                this.startLoop();
                this.idle_time = 0;
            }
        }
        else {
            this.idle_time = 0;
        }
    }

    async stopLoop() {
        // you can call this without await if you don't need to wait for it to finish
        if (this.interrupt)
            return;
        console.log('stopping self-prompt loop')
        this.interrupt = true;
        while (this.loop_active) {
            await new Promise(r => setTimeout(r, 500));
        }
        this.interrupt = false;
    }

    async stop(stop_action=true) {
        this.interrupt = true;
        if (stop_action)
            await this.agent.actions.stop();
        this.stopLoop();
        this.state = STOPPED;
    }

    async pause() {
        this.interrupt = true;
        await this.agent.actions.stop();
        this.stopLoop();
        this.state = PAUSED;
    }

    shouldInterrupt(is_self_prompt) { // to be called from handleMessage
        return is_self_prompt && (this.state === ACTIVE || this.state === PAUSED) && this.interrupt;
    }

    handleUserPromptedCmd(is_self_prompt, is_action) {
        // if a user messages and the bot responds with an action, stop the self-prompt loop
        if (!is_self_prompt && is_action) {
            this.stopLoop();
            // this stops it from responding from the handlemessage loop and the self-prompt loop at the same time
        }
    }
}